[package]
name = "simulation_rust"
version = "0.1.0"
authors = ["Mitchell Berendhuysen <mitchellbhuysen@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"

